- lineinfile: dest=/etc/hosts regexp='^127.0.1.1' line='127.0.1.1 {{hostname}}'
  when: hostname|default(false)
  sudo: true
  notify: restart networking
- file: contents={{hostname}} path=/etc/hostname
  when: hostname|default(false)
  sudo: true
  notify: restart networking
