x11vnc_options:
- "-noxdamage"
- "-noxfixes"
- "-noxrecord"
- "-rfbport 5900"
- "-display :0"
- "-shared"
- "-avahi"
- "-usepw"
# cache doesn't work with OSX screenshairng app #- "-ncache 4"
#- "-ssl"
x11vnc_passwd: raspberry
